# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Distill < Formula
  desc "Turn Claude Code session transcripts into a curated model of you"
  homepage "https://github.com/msmedes/distill"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/msmedes/distill/releases/download/v0.1.0/distill_0.1.0_darwin_x86_64.tar.gz"
      sha256 "0df5a3b7b57548e6d1a70de049619498be5fe007dd2b8f20a1742a884105c986"

      define_method(:install) do
        bin.install "distill"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/msmedes/distill/releases/download/v0.1.0/distill_0.1.0_darwin_arm64.tar.gz"
      sha256 "0bce614b4651ab30329d19b79dc7994910c46d4cb3a80b7ce23d0012afdacf3a"

      define_method(:install) do
        bin.install "distill"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/msmedes/distill/releases/download/v0.1.0/distill_0.1.0_linux_x86_64.tar.gz"
      sha256 "7191434aacaf007ec89bf0c4ecaab78865e896ab83ed14068c1b6719fa342a1a"
      define_method(:install) do
        bin.install "distill"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/msmedes/distill/releases/download/v0.1.0/distill_0.1.0_linux_arm64.tar.gz"
      sha256 "8691c774ff8331b2b999fd3e20a72aebbc64c380007593cf7ed47c44f47d526e"
      define_method(:install) do
        bin.install "distill"
      end
    end
  end

  def caveats
    <<~EOS
      distill calls the `claude` CLI at runtime for all LLM work — install
      Claude Code first and sign in:

        https://docs.claude.com/en/docs/claude-code

      To auto-extract on every session end (optional, recommended):

        distill install

      Your local state lives at ~/.distill/.
    EOS
  end

  test do
    system "#{bin}/distill", "help"
  end
end
