# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Distill < Formula
  desc "Turn Claude Code session transcripts into a curated model of you"
  homepage "https://github.com/msmedes/distill"
  version "0.2.13"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/msmedes/distill/releases/download/v0.2.13/distill_0.2.13_darwin_x86_64.tar.gz"
      sha256 "3de8478d459e4035f466ea21692c122c1e968c09bc76baa5f4915604fe059132"

      define_method(:install) do
        bin.install "distill"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/msmedes/distill/releases/download/v0.2.13/distill_0.2.13_darwin_arm64.tar.gz"
      sha256 "29b776645f1407cca85a4769a9a281111ae410d6e3a346b0af481a1f5c05476d"

      define_method(:install) do
        bin.install "distill"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/msmedes/distill/releases/download/v0.2.13/distill_0.2.13_linux_x86_64.tar.gz"
      sha256 "fd4d77612ae932a9023267ed2a0448950658611c260b752ec60bb983f9211f19"
      define_method(:install) do
        bin.install "distill"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/msmedes/distill/releases/download/v0.2.13/distill_0.2.13_linux_arm64.tar.gz"
      sha256 "59699e07a98316d25de07290e864b25bcf8a0091706056eee64e38c0b249a9a2"
      define_method(:install) do
        bin.install "distill"
      end
    end
  end

  def post_install
    # Restart the watcher only if it was already running, so upgrades pick
    # up the new binary. Using `launchctl kickstart` (not `brew services
    # restart`) avoids the plist-write permission error you hit when
    # brew-from-brew tries to rewrite the LaunchAgent during an upgrade.
    if OS.mac? && `brew services list 2>/dev/null`.match?(/^(msmedes\/distill\/)?distill\s+started/)
      label = "homebrew.mxcl.distill"
      plist = "#{Dir.home}/Library/LaunchAgents/#{label}.plist"
      if File.exist?(plist)
        system "launchctl", "kickstart", "-k", "gui/#{Process.uid}/#{label}"
      end
    end
  end

  def caveats
    <<~EOS
      distill calls the `claude` CLI at runtime for all LLM work — install
      Claude Code first and sign in:

        https://docs.claude.com/en/docs/claude-code

      To configure distill:

        distill install

      To run the watcher automatically with Homebrew:

        brew services start distill

      Your local state lives at ~/.distill/.
    EOS
  end

  service do
    run [opt_bin/"distill", "watch"]
    keep_alive true
    run_at_load true
    log_path var/"log/distill.log"
    error_log_path var/"log/distill.log"
  end

  test do
    system "#{bin}/distill", "help"
  end
end
