# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Distill < Formula
  desc "Turn Claude Code session transcripts into a curated model of you"
  homepage "https://github.com/msmedes/distill"
  version "0.2.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/msmedes/distill/releases/download/v0.2.7/distill_0.2.7_darwin_x86_64.tar.gz"
      sha256 "9819a9683d18e48439ec438d4c6ee98b71456c5ae6e3a78a3af2f7aa62645931"

      define_method(:install) do
        bin.install "distill"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/msmedes/distill/releases/download/v0.2.7/distill_0.2.7_darwin_arm64.tar.gz"
      sha256 "5a7dfb5431f39bb556bf515577f1ed4c53cfef22f6c0e47320c6ca0ec1f05953"

      define_method(:install) do
        bin.install "distill"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/msmedes/distill/releases/download/v0.2.7/distill_0.2.7_linux_x86_64.tar.gz"
      sha256 "9638eac92c5724b11280fd83ee27c07ccf18e11dc506748b76e627aba9d0061a"
      define_method(:install) do
        bin.install "distill"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/msmedes/distill/releases/download/v0.2.7/distill_0.2.7_linux_arm64.tar.gz"
      sha256 "05cee3daaaba95b4b56c73e5d51b90c84a69c375d6d83aae40676b156d567fba"
      define_method(:install) do
        bin.install "distill"
      end
    end
  end

  def post_install
    # Restart the watcher only if it was already running, so upgrades pick
    # up the new binary. Using `launchctl kickstart` (not `brew services
    # restart`) avoids the plist-write permission error you hit when
    # brew-from-brew tries to rewrite the LaunchAgent during an upgrade.
    if OS.mac? && `brew services list 2>/dev/null`.match?(/^(msmedes\/distill\/)?distill\s+started/)
      label = "homebrew.mxcl.distill"
      plist = "#{Dir.home}/Library/LaunchAgents/#{label}.plist"
      if File.exist?(plist)
        system "launchctl", "kickstart", "-k", "gui/#{Process.uid}/#{label}"
      end
    end
  end

  def caveats
    <<~EOS
      distill calls the `claude` CLI at runtime for all LLM work — install
      Claude Code first and sign in:

        https://docs.claude.com/en/docs/claude-code

      To configure distill:

        distill install

      To run the watcher automatically with Homebrew:

        brew services start distill

      Your local state lives at ~/.distill/.
    EOS
  end

  service do
    run [opt_bin/"distill", "watch"]
    keep_alive true
    run_at_load true
    log_path var/"log/distill.log"
    error_log_path var/"log/distill.log"
  end

  test do
    system "#{bin}/distill", "help"
  end
end
