# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Distill < Formula
  desc "Turn Claude Code session transcripts into a curated model of you"
  homepage "https://github.com/msmedes/distill"
  version "0.2.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/msmedes/distill/releases/download/v0.2.4/distill_0.2.4_darwin_x86_64.tar.gz"
      sha256 "ad8a7b6f64cea097c7ea1426896138429db21f09612c77e72ffc9c35e232641e"

      define_method(:install) do
        bin.install "distill"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/msmedes/distill/releases/download/v0.2.4/distill_0.2.4_darwin_arm64.tar.gz"
      sha256 "0d0d4b5a10f3336df2bad91e838d7bb19c05dd8adb0ec3453daf053f1034fcca"

      define_method(:install) do
        bin.install "distill"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/msmedes/distill/releases/download/v0.2.4/distill_0.2.4_linux_x86_64.tar.gz"
      sha256 "46a4eac7d79e6a8f300d30628a674d1d565c8bdc41e779ac4df5a51a5afa4e3b"
      define_method(:install) do
        bin.install "distill"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/msmedes/distill/releases/download/v0.2.4/distill_0.2.4_linux_arm64.tar.gz"
      sha256 "dfd69023fe2dcaa4ab92e8c83f267c4d19e54001b6aa0422113a74f4b4e68f9b"
      define_method(:install) do
        bin.install "distill"
      end
    end
  end

  def post_install
    if `brew services list 2>/dev/null`.match?(/^(msmedes\/distill\/)?distill\s+started/)
      system "brew", "services", "restart", "msmedes/distill/distill"
    end
  end

  def caveats
    <<~EOS
      distill calls the `claude` CLI at runtime for all LLM work — install
      Claude Code first and sign in:

        https://docs.claude.com/en/docs/claude-code

      To configure distill:

        distill install

      To run the watcher automatically with Homebrew:

        brew services start distill

      Your local state lives at ~/.distill/.
    EOS
  end

  service do
    run [opt_bin/"distill", "watch"]
    keep_alive true
    run_at_load true
    log_path var/"log/distill.log"
    error_log_path var/"log/distill.log"
  end

  test do
    system "#{bin}/distill", "help"
  end
end
